[CmdletBinding()]param([string]$RepositoryRoot=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path)
Set-StrictMode -Version 2.0;$ErrorActionPreference='Stop'
$runner=Join-Path $RepositoryRoot 'Modules\ObjectControl\Invoke-MSADPTDirectoryControlEffectiveAccess-v1.0.1.ps1';if(-not(Test-Path $runner)){throw 'RunnerMissing'}
$t=$null;$e=$null;[void][Management.Automation.Language.Parser]::ParseFile($runner,[ref]$t,[ref]$e);if(@($e).Count){throw "ParserFailure: $(@($e|ForEach-Object{$_.Message})-join'; ')"}
$temp=Join-Path ([IO.Path]::GetTempPath()) ('MSADPT-EA101-'+[guid]::NewGuid().ToString('N'));$ev=Join-Path $temp 'evidence';$red=Join-Path $temp 'reduction';$out=Join-Path $temp 'out';New-Item -ItemType Directory -Path $ev,$red|Out-Null
try{
 $user='S-1-5-21-1-1100';$allowGroup='S-1-5-21-1-2100';$denyGroup='S-1-5-21-1-2200';$dn1='CN=Tier0,DC=example,DC=test';$dn2='CN=Server1,DC=example,DC=test';$dn3='CN=Server2,DC=example,DC=test'
 @([pscustomobject]@{CandidateId='NestedAllow';Priority='P1';Trustee='EXAMPLE\User';TrusteeSid=$user;TargetName='Tier0';TargetDistinguishedName=$dn1;TargetObjectType='Group';Capability='GenericAll'},[pscustomobject]@{CandidateId='NestedDeny';Priority='P1';Trustee='EXAMPLE\User';TrusteeSid=$user;TargetName='Server1';TargetDistinguishedName=$dn2;TargetObjectType='Computer';Capability='WriteRBCD'},[pscustomobject]@{CandidateId='Incomplete';Priority='P2';Trustee='EXAMPLE\Other';TrusteeSid='S-1-5-21-1-1200';TargetName='Server2';TargetDistinguishedName=$dn3;TargetObjectType='Computer';Capability='WriteRBCD'})|Export-Csv (Join-Path $red 'directory-control-prioritized-target-details.csv') -NoTypeInformation
 @([pscustomobject]@{TargetObjectType='Group';TargetName='Tier0';TargetDistinguishedName=$dn1;Trustee='EXAMPLE\AllowGroup';TrusteeSid=$allowGroup;AccessControlType='Allow';ActiveDirectoryRights='GenericAll';ObjectTypeGuid='00000000-0000-0000-0000-000000000000';InheritedObjectTypeGuid='00000000-0000-0000-0000-000000000000';IsInherited=$false},[pscustomobject]@{TargetObjectType='Computer';TargetName='Server1';TargetDistinguishedName=$dn2;Trustee='EXAMPLE\AllowGroup';TrusteeSid=$allowGroup;AccessControlType='Allow';ActiveDirectoryRights='WriteProperty';ObjectTypeGuid='3f78c3e5-f79a-46bd-a0b8-9d18116ddc79';InheritedObjectTypeGuid='00000000-0000-0000-0000-000000000000';IsInherited=$false},[pscustomobject]@{TargetObjectType='Computer';TargetName='Server1';TargetDistinguishedName=$dn2;Trustee='EXAMPLE\DenyGroup';TrusteeSid=$denyGroup;AccessControlType='Deny';ActiveDirectoryRights='WriteProperty';ObjectTypeGuid='3f78c3e5-f79a-46bd-a0b8-9d18116ddc79';InheritedObjectTypeGuid='00000000-0000-0000-0000-000000000000';IsInherited=$false},[pscustomobject]@{TargetObjectType='Computer';TargetName='Server2';TargetDistinguishedName=$dn3;Trustee='EXAMPLE\Other';TrusteeSid='S-1-5-21-1-1200';AccessControlType='Allow';ActiveDirectoryRights='WriteProperty';ObjectTypeGuid='3f78c3e5-f79a-46bd-a0b8-9d18116ddc79';InheritedObjectTypeGuid='00000000-0000-0000-0000-000000000000';IsInherited=$false})|Export-Csv (Join-Path $ev 'directory-control-ace-inventory.csv') -NoTypeInformation
 @([pscustomobject]@{PrincipalSid=$user;TokenSid=$user;Source='Self';Complete=$true},[pscustomobject]@{PrincipalSid=$user;TokenSid=$allowGroup;Source='DirectGroup';Complete=$true},[pscustomobject]@{PrincipalSid=$user;TokenSid=$denyGroup;Source='NestedGroup';Complete=$true},[pscustomobject]@{PrincipalSid='S-1-5-21-1-1200';TokenSid='S-1-5-21-1-1200';Source='Self';Complete=$false})|Export-Csv (Join-Path $temp 'token.csv') -NoTypeInformation
 $null=& $runner -DirectoryControlEvidenceDirectory $ev -CandidateReductionDirectory $red -OutputDirectory $out -TokenEvidencePath (Join-Path $temp 'token.csv') -NoColor
 $rows=@(Import-Csv (Join-Path $out 'directory-control-effective-access-evaluations.csv'));if(@($rows|Where-Object{$_.CandidateId-eq'NestedAllow'}).Disposition-ne'EffectiveControlConfirmed'){throw 'NestedAllowFailed'};if(@($rows|Where-Object{$_.CandidateId-eq'NestedDeny'}).Disposition-ne'EffectiveControlNotEstablished'){throw 'NestedDenyFailed'};if(@($rows|Where-Object{$_.CandidateId-eq'Incomplete'}).Disposition-ne'Inconclusive'){throw 'IncompleteTokenFailed'};$trace=@(Import-Csv (Join-Path $out 'directory-control-effective-access-ace-trace.csv'));if(@($trace|Where-Object{$_.AceTrusteeSid-eq$denyGroup}).Count-ne1){throw 'DenyTraceFailed'}
 [pscustomobject]@{Status='Passed';TestVersion='1.0.1';NestedAllow=$true;NestedDeny=$true;IncompleteTokenConservative=$true;AceTrace=$true;NetworkActivity='None';RemoteChanges='None'}
}finally{Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}
