<# .SYNOPSIS Tests generic ADCS planner v0.4.0. .NOTES Version: 1.0.1 #>
[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$PlannerPath,[Parameter(Mandatory=$true)][string]$OutputRoot)
Set-StrictMode -Version 2.0;$ErrorActionPreference='Stop';$Tok=$null;$Err=$null;$null=[Management.Automation.Language.Parser]::ParseFile($PlannerPath,[ref]$Tok,[ref]$Err);if($Err.Count -gt 0){throw($Err.Message-join'; ')}
if(Test-Path $OutputRoot){Remove-Item $OutputRoot -Recurse -Force};New-Item -ItemType Directory -Path $OutputRoot -Force|Out-Null
function F($id,$state){[pscustomobject]@{id=$id;state=$state;rationale='s'}}
function C($tech,$principal,$facts){[pscustomobject]@{candidateId="$tech|CA|T|$principal";technique=$tech;certificationAuthority='CA';template='T';principal=$principal;identityCategory='SecurityGroup';disposition='Incomplete evidence';requiredCount=$facts.Count;satisfiedRequiredCount=@($facts|Where-Object{$_.state -eq 'Confirmed'}).Count;missingOrInconclusive=@($facts|Where-Object{$_.state -eq 'Inconclusive'});notObserved=@($facts|Where-Object{$_.state -eq 'Not observed'});facts=$facts;safeFollowUp='s'}}
$Candidates=@((C 'ESC2' 'P' @((F 'anyPurposeOrNoEkuRestriction' 'Confirmed'),(F 'effectiveLowPrivilegeEnrollment' 'Inconclusive'))),(C 'ESC3' 'P' @((F 'certificateRequestAgentEku' 'Confirmed'),(F 'enrollmentAgentRestrictionsPermitRoute' 'Inconclusive'),(F 'targetTemplateChainResolved' 'Inconclusive'))),(C 'ESC13' 'P' @((F 'issuancePolicyOidPresent' 'Inconclusive'),(F 'oidToGroupLinkPresent' 'Inconclusive'))),(C 'ESC15' 'P' @((F 'affectedVersionOneTemplate' 'Confirmed'),(F 'requesterControlsCertificateIdentity' 'Confirmed'),(F 'relevantPatchState' 'Inconclusive'))),(C 'ESC1' 'ADMIN' @((F 'effectiveLowPrivilegeEnrollment' 'Inconclusive'))),(C 'ESC4' 'P' @((F 'effectiveNonPrivilegedTemplateControl' 'Inconclusive'))),[pscustomobject]@{candidateId='ESC1|CA|Blocked|P';technique='ESC1';certificationAuthority='CA';template='Blocked';principal='P';identityCategory='SecurityGroup';disposition='Blocked';requiredCount=1;satisfiedRequiredCount=0;missingOrInconclusive=@();notObserved=@((F 'effectiveLowPrivilegeEnrollment' 'Not observed'));facts=@((F 'effectiveLowPrivilegeEnrollment' 'Not observed'));safeFollowUp='s'})
$Contexts=@([pscustomobject]@{identityReference='P';category='SecurityGroup';validationPriorityModifier=20;isPrivilegedContext=$false},[pscustomobject]@{identityReference='ADMIN';category='PrivilegedAdministrative';validationPriorityModifier=-60;isPrivilegedContext=$true})
$P1=Join-Path $OutputRoot 'c.json';$P2=Join-Path $OutputRoot 'i.json';$Out=Join-Path $OutputRoot 'out';$Candidates|ConvertTo-Json -Depth 8|Set-Content $P1;$Contexts|ConvertTo-Json -Depth 5|Set-Content $P2
$Objects=@(& $PlannerPath -CandidateInventoryPath $P1 -IdentityContextPath $P2 -OutputDirectory $Out -TopCandidateCount 6 -Quiet);$R=@($Objects|Where-Object{$null -ne $_ -and $null -ne $_.PSObject.Properties['plannerVersion'] -and $null -ne $_.PSObject.Properties['status'] -and [string]$_.status -eq 'Completed'})|Select-Object -Last 1;if($null -eq $R){throw'Terminal missing'}
$Plan=@(Get-Content (Join-Path $Out 'adcs-validation-plan.json') -Raw|ConvertFrom-Json);$Lan=Get-Content (Join-Path $Out 'adcs-next-lan-plan.json') -Raw|ConvertFrom-Json
$Checks=@([pscustomobject]@{Test='SevenCandidates';Passed=$Plan.Count -eq 7},[pscustomobject]@{Test='AllTechniques';Passed=@($Plan.technique|Sort-Object -Unique).Count -eq 6},[pscustomobject]@{Test='Esc3Capability';Passed=@($Plan|Where-Object{$_.technique -eq 'ESC3' -and $_.esc3AgentEkuCapability}).Count -eq 1},[pscustomobject]@{Test='Esc13SchemaAction';Passed=@($Lan.consolidatedEvidenceActions|Where-Object{$_.actionKey -eq 'ESC13-TemplateIssuancePolicyCollection'}).Count -eq 1},[pscustomobject]@{Test='PrivilegedDeprioritized';Passed=(@($Plan|Where-Object{$_.principal -eq 'ADMIN'})[0].rank -gt 1)},[pscustomobject]@{Test='ZeroActionCandidateSafe';Passed=(@(@($Plan|Where-Object{$_.candidateId -eq 'ESC1|CA|Blocked|P'})[0].validationActionKeys).Count -eq 0)},[pscustomobject]@{Test='Outputs';Passed=@($R.evidence|Where-Object{Test-Path $_}).Count -eq 4})
$Failed=@($Checks|Where-Object{-not $_.Passed});if($Failed.Count -gt 0){$Failed|Format-List;throw"$($Failed.Count) planner tests failed"};[pscustomobject]@{Status='Passed';TestCount=$Checks.Count;PlannerVersion='0.4.1';TestVersion='1.0.1'}
