[CmdletBinding()]param([string]$RepositoryRoot=(Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))
Set-StrictMode -Version 2.0;$ErrorActionPreference='Stop'
$parser=Join-Path $RepositoryRoot 'Modules\ADHealth\ConvertFrom-MSADPTADHealthOutput-v1.0.0.ps1';$merge=Join-Path $RepositoryRoot 'Modules\ADHealth\Merge-MSADPTADHealthEvidence-v1.0.0.ps1';$report=Join-Path $RepositoryRoot 'Modules\ADHealth\New-MSADPTADHealthReport-v1.0.0.ps1';$fx=Join-Path $RepositoryRoot 'Tests\Fixtures\ADHealth';$temp=Join-Path ([IO.Path]::GetTempPath()) ('MSADPT-ADHealth-Test-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory $temp|Out-Null
try{
$cases=@(
@{Tool='DCDiag';File='DCDiag-Healthy.txt';Collection='Complete';Health='ConfirmedHealthy'},@{Tool='DCDiag';File='DCDiag-AccessDenied.txt';Collection='AccessDenied';Health='Inconclusive'},@{Tool='Repadmin';File='Repadmin-Healthy.txt';Collection='Complete';Health='ConfirmedHealthy'},@{Tool='Repadmin';File='Repadmin-Usage.txt';Collection='Unrecognized';Health='Inconclusive'},@{Tool='Nltest';File='Nltest-Healthy.txt';Collection='Complete';Health='ConfirmedHealthy'},@{Tool='W32tm';File='W32tm-AccessDenied.txt';Collection='AccessDenied';Health='Inconclusive'},@{Tool='EventLog';File='EventLog-Zero.txt';Collection='Complete';Health='NotDetected'})
$out=@();$i=0;foreach($c in $cases){$i++;$r=& $parser -Tool $c.Tool -InputPath (Join-Path $fx $c.File) -Target 'DC01';if($r.CollectionStatus-ne$c.Collection){throw "Collection mismatch $($c.File)"};if($r.HealthDisposition-ne$c.Health){throw "Health mismatch $($c.File): $($r.HealthDisposition)"};$p=Join-Path $temp "$i.json";$r|ConvertTo-Json -Depth 10|Set-Content $p -Encoding UTF8;$out+=$p}
$m=& $merge -InputPath $out -ExpectedTarget @('DC01','DC02');if($m.OverallDisposition-ne'Inconclusive'){throw 'Expected incomplete target coverage to be Inconclusive'};if('DC02'-notin @($m.MissingTargets)){throw 'Missing target not detected'};$mp=Join-Path $temp 'merged.json';$m|ConvertTo-Json -Depth 20|Set-Content $mp -Encoding UTF8;$hp=Join-Path $temp 'ADHealth.html';& $report -InputPath $mp -OutputPath $hp|Out-Null;if(-not(Test-Path $hp)){throw 'HTML not generated'};$ht=Get-Content $hp -Raw;if($ht-notmatch'MSADPT AD Health' -or $ht-notmatch'Missing targets'){throw 'HTML contract failed'}
[pscustomobject]@{Status='Passed';TestVersion='1.0.0';ScenarioCount=$cases.Count;MissingTargetDetection=$true;HtmlGenerated=$true;NetworkActivity='None';ActiveDirectoryQueries='None';RemoteChanges='None'}
}finally{Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}
