<# .SYNOPSIS Tests the offline ADCS prerequisite correlator. .NOTES Version: 1.0.1 #>
[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$CatalogPath,[Parameter(Mandatory=$true)][string]$EnginePath,[Parameter(Mandatory=$true)][string]$FixtureGeneratorPath,[Parameter(Mandatory=$true)][string]$OutputRoot)
Set-StrictMode -Version 2.0;$ErrorActionPreference='Stop'
foreach($Path in @($CatalogPath,$EnginePath,$FixtureGeneratorPath)){if(-not(Test-Path -LiteralPath $Path -PathType Leaf)){throw "Required file not found: $Path"}}
if(Test-Path -LiteralPath $OutputRoot){Remove-Item -LiteralPath $OutputRoot -Recurse -Force}
$FixtureRoot=Join-Path $OutputRoot 'Fixtures';$Generation=& $FixtureGeneratorPath -OutputDirectory $FixtureRoot;$Index=@(Get-Content -LiteralPath $Generation.IndexPath -Raw|ConvertFrom-Json)
$Expected=@{IncompleteCollection=@{ESC1='Incomplete evidence'};Esc1Satisfied=@{ESC1='Prerequisites satisfied'};Esc1BlockedByApproval=@{ESC1='Blocked'};Esc6FlagWithoutEnrollment=@{ESC6='Blocked'};Esc11IncompleteRuntime=@{ESC11='Incomplete evidence'}}
$Results=foreach($Scenario in $Index){$Out=Join-Path $OutputRoot ('Results\'+$Scenario.Scenario);$Terminal=@(& $EnginePath -CatalogPath $CatalogPath -FactsPath $Scenario.FactsPath -OutputDirectory $Out)|Where-Object{$null-ne$_.PSObject.Properties['engineVersion']}|Select-Object -Last 1;$Candidates=@(Get-Content -LiteralPath (Join-Path $Out 'adcs-technique-candidates.json') -Raw|ConvertFrom-Json);foreach($Check in $Expected[[string]$Scenario.Scenario].GetEnumerator()){$Candidate=$Candidates|Where-Object Technique -eq $Check.Key|Select-Object -First 1;[pscustomobject]@{Scenario=$Scenario.Scenario;Technique=$Check.Key;Expected=$Check.Value;Actual=$Candidate.Disposition;Passed=([string]$Candidate.Disposition -eq [string]$Check.Value);TechniqueCount=$Terminal.techniqueCount}}}
$Results|Format-Table -AutoSize;$Failed=@($Results|Where-Object{-not $_.Passed});if($Failed.Count -gt 0){throw "$($Failed.Count) prerequisite correlation test(s) failed."};$Catalog=Get-Content -LiteralPath $CatalogPath -Raw|ConvertFrom-Json;if(@($Catalog.techniques).Count -ne 16){throw "Expected 16 techniques but found $(@($Catalog.techniques).Count)."};[pscustomobject]@{Status='Passed';TestCount=$Results.Count;TechniqueCount=16;CatalogVersion=$Catalog.catalogVersion;EngineVersion='0.1.1';OutputRoot=$OutputRoot}
