<#
.SYNOPSIS
Runs the complete saved-evidence AD Health pipeline without network or AD access.
.NOTES
Version: 1.1.0
#>
[CmdletBinding()]
param([Parameter(Mandatory)][string]$EvidenceRoot,[Parameter(Mandatory)][string]$OutputRoot,[string[]]$ExpectedTarget=@(),[string]$ExpectedTargetPath)
Set-StrictMode -Version 2.0;$ErrorActionPreference='Stop';$started=(Get-Date).ToUniversalTime();$moduleRoot=$PSScriptRoot
$importer=Join-Path $moduleRoot 'Import-MSADPTADHealthEvidence-v1.1.0.ps1';$parser=Join-Path $moduleRoot 'ConvertFrom-MSADPTADHealthOutput-v1.0.0.ps1';$complete=Join-Path $moduleRoot 'Test-MSADPTADHealthEvidenceCompleteness-v1.1.0.ps1';$merge=Join-Path $moduleRoot 'Merge-MSADPTADHealthEvidence-v1.0.0.ps1';$report=Join-Path $moduleRoot 'New-MSADPTADHealthReport-v1.0.0.ps1'
$OutputRoot=[IO.Path]::GetFullPath($OutputRoot);$normal=Join-Path $OutputRoot 'Normalized';New-Item -ItemType Directory $normal -Force|Out-Null
$manifestArgs=@{EvidenceRoot=$EvidenceRoot;ExpectedTarget=$ExpectedTarget};if($ExpectedTargetPath){$manifestArgs.ExpectedTargetPath=$ExpectedTargetPath};$manifest=& $importer @manifestArgs;$manifestPath=Join-Path $OutputRoot 'ADHealth-ImportManifest.json';$manifest|ConvertTo-Json -Depth 15|Set-Content $manifestPath -Encoding UTF8
$coverage=& $complete -ManifestPath $manifestPath;$coveragePath=Join-Path $OutputRoot 'ADHealth-Coverage.json';$coverage|ConvertTo-Json -Depth 15|Set-Content $coveragePath -Encoding UTF8
$normalized=New-Object 'System.Collections.Generic.List[object]';$normalizedPaths=New-Object 'System.Collections.Generic.List[string]';$index=0
foreach($item in @($manifest.Items)){ $index++;if($item.Supported){$r=& $parser -Tool $item.Tool -InputPath $item.Path -Target $item.Target;$r|Add-Member NoteProperty EvidenceSubtype $item.Subtype;$r|Add-Member NoteProperty SourceRelativePath $item.RelativePath}else{$r=[pscustomobject][ordered]@{SchemaVersion='1.1';Tool='Unsupported';Target='Unknown';ExecutionStatus='NotExecuted';CollectionStatus='Unrecognized';HealthDisposition='Inconclusive';ExitCode=$null;RawOutputPath=$item.Path;RawOutputSHA256=$item.SHA256;ParserVersion='1.1.0';EvidenceSubtype=$item.Subtype;SourceRelativePath=$item.RelativePath;ObservedFacts=@();Limitations=@($item.Reason);RecommendedFollowUp='Rename or supply explicit supported metadata before ingestion.'}}
 $safe=('{0:D4}-{1}-{2}-{3}.json'-f $index,($r.Tool-replace'[^A-Za-z0-9]','_'),($r.Target-replace'[^A-Za-z0-9._-]','_'),($r.EvidenceSubtype-replace'[^A-Za-z0-9._-]','_'));$np=Join-Path $normal $safe;$r|ConvertTo-Json -Depth 12|Set-Content $np -Encoding UTF8;$normalized.Add($r);$normalizedPaths.Add($np)}
$mergePaths=@($normalizedPaths.ToArray());if($mergePaths.Count){$assessment=& $merge -InputPath $mergePaths -ExpectedTarget @($manifest.ExpectedTargets)}else{$assessment=[pscustomobject][ordered]@{SchemaVersion='1.1';OverallDisposition='Inconclusive';EvidenceCount=0;ExpectedTargetCount=@($manifest.ExpectedTargets).Count;ObservedTargetCount=0;MissingTargets=@($manifest.ExpectedTargets);ConfirmedUnhealthyCount=0;InconclusiveCount=0;ConflictCount=0;Conflicts=@();Evidence=@();Limitations=@('No evidence files were normalized.')}}
$assessment|Add-Member NoteProperty Coverage $coverage;$assessment|Add-Member NoteProperty PipelineVersion '1.1.0';$assessmentPath=Join-Path $OutputRoot 'ADHealth-Assessment.json';$assessment|ConvertTo-Json -Depth 30|Set-Content $assessmentPath -Encoding UTF8
@($normalized.ToArray())|Select-Object Target,Tool,EvidenceSubtype,ExecutionStatus,CollectionStatus,HealthDisposition,ExitCode,RawOutputSHA256,RawOutputPath|Export-Csv (Join-Path $OutputRoot 'ADHealth-Evidence.csv') -NoTypeInformation -Encoding UTF8
@([pscustomobject]@{ExpectedTargetSource=$coverage.ExpectedTargetSource;CompletenessClaimsAllowed=$coverage.CompletenessClaimsAllowed;ExpectedTargetCount=$coverage.ExpectedTargetCount;ObservedTargetCount=$coverage.ObservedTargetCount;MissingTargets=($coverage.MissingTargets-join'; ');CoverageDisposition=$coverage.CoverageDisposition;DuplicateGroupCount=$coverage.DuplicateGroupCount;UnsupportedFileCount=$coverage.UnsupportedFileCount})|Export-Csv (Join-Path $OutputRoot 'ADHealth-Coverage.csv') -NoTypeInformation -Encoding UTF8
@($assessment.Conflicts)|Select-Object Key,@{n='Dispositions';e={$_.Dispositions-join'; '}}|Export-Csv (Join-Path $OutputRoot 'ADHealth-Conflicts.csv') -NoTypeInformation -Encoding UTF8
$html=Join-Path $OutputRoot 'MSADPT-AD-Health.html';& $report -InputPath $assessmentPath -OutputPath $html|Out-Null
$finished=(Get-Date).ToUniversalTime();$stage=[pscustomobject][ordered]@{SchemaVersion='1.1';Stage='ADHealthOfflineAssessment';Status='Succeeded';Disposition=$assessment.OverallDisposition;StartedUtc=$started.ToString('o');CompletedUtc=$finished.ToString('o');DurationMilliseconds=[math]::Round(($finished-$started).TotalMilliseconds);EvidenceRoot=(Resolve-Path -LiteralPath $EvidenceRoot).Path;OutputRoot=$OutputRoot;DiscoveredFileCount=$manifest.DiscoveredFileCount;NormalizedEvidenceCount=$normalized.Count;CompletenessClaimsAllowed=$coverage.CompletenessClaimsAllowed;CoverageDisposition=$coverage.CoverageDisposition;NetworkActivity='None';ActiveDirectoryQueries='None';RemoteChanges='None';Outputs=[pscustomobject]@{Assessment=$assessmentPath;EvidenceCsv=(Join-Path $OutputRoot 'ADHealth-Evidence.csv');CoverageCsv=(Join-Path $OutputRoot 'ADHealth-Coverage.csv');ConflictsCsv=(Join-Path $OutputRoot 'ADHealth-Conflicts.csv');Html=$html;Normalized=$normal}}
$stage|ConvertTo-Json -Depth 12|Set-Content (Join-Path $OutputRoot 'ADHealth-StageStatus.json') -Encoding UTF8;$stage
