<# .SYNOPSIS Creates a concise standalone AD Health HTML report. .NOTES Version: 1.0.0 #>
[CmdletBinding()]
param([Parameter(Mandatory)][string]$InputPath,[Parameter(Mandatory)][string]$OutputPath)
Set-StrictMode -Version 2.0;$ErrorActionPreference='Stop';$m=Get-Content -LiteralPath $InputPath -Raw|ConvertFrom-Json
function ConvertTo-MSADPTHtmlText{param([AllowNull()][object]$Value);[Net.WebUtility]::HtmlEncode([string]$Value)}
$rows=foreach($e in @($m.Evidence)){"<tr><td>$(ConvertTo-MSADPTHtmlText $e.Target)</td><td>$(ConvertTo-MSADPTHtmlText $e.Tool)</td><td>$(ConvertTo-MSADPTHtmlText $e.ExecutionStatus)</td><td>$(ConvertTo-MSADPTHtmlText $e.CollectionStatus)</td><td>$(ConvertTo-MSADPTHtmlText $e.HealthDisposition)</td><td>$(ConvertTo-MSADPTHtmlText ($e.Limitations -join '; '))</td><td><code>$(ConvertTo-MSADPTHtmlText $e.RawOutputPath)</code></td></tr>"}
$missing=if(@($m.MissingTargets).Count){ConvertTo-MSADPTHtmlText ($m.MissingTargets -join ', ')}else{'None'}
$html=@"
<!doctype html><html><head><meta charset="utf-8"><title>MSADPT AD Health</title><style>body{font-family:Segoe UI,Arial;margin:28px;color:#1f2937}h1{margin-bottom:4px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card{border:1px solid #d1d5db;border-radius:10px;padding:14px}.big{font-size:24px;font-weight:700}table{border-collapse:collapse;width:100%;margin-top:18px}th,td{border:1px solid #d1d5db;padding:8px;vertical-align:top}th{background:#f3f4f6;text-align:left}code{font-size:11px}.note{background:#fff7ed;border-left:4px solid #f97316;padding:10px}</style></head><body><h1>MSADPT AD Health</h1><p>Evidence-first posture summary. Collection failures are not presented as domain-controller health failures.</p><div class="cards"><div class="card"><div>Overall</div><div class="big">$(ConvertTo-MSADPTHtmlText $m.OverallDisposition)</div></div><div class="card"><div>Evidence</div><div class="big">$($m.EvidenceCount)</div></div><div class="card"><div>Unhealthy</div><div class="big">$($m.ConfirmedUnhealthyCount)</div></div><div class="card"><div>Inconclusive</div><div class="big">$($m.InconclusiveCount)</div></div></div><h2>Coverage</h2><p>Observed targets: $($m.ObservedTargetCount) / Expected targets: $($m.ExpectedTargetCount)</p><p class="note"><strong>Missing targets:</strong> $missing</p><h2>Evidence matrix</h2><table><thead><tr><th>Target</th><th>Tool</th><th>Execution</th><th>Collection</th><th>Health</th><th>Limitations</th><th>Raw evidence</th></tr></thead><tbody>$($rows -join "`n")</tbody></table></body></html>
"@
$parent=Split-Path -Parent $OutputPath;if($parent){New-Item -ItemType Directory -Path $parent -Force|Out-Null};[IO.File]::WriteAllText([IO.Path]::GetFullPath($OutputPath),$html,(New-Object Text.UTF8Encoding($false)));Get-Item -LiteralPath $OutputPath
