<#
.SYNOPSIS
Correlates MSADPT AD object-control evidence into deduplicated semantic attack-path candidates.
.DESCRIPTION
Consumes dangerous-ace-inventory.json generated by the MSADPT object-control baseline. Resolves known
high-impact AD attribute and control-access GUIDs, suppresses routine and non-actionable records,
separates inherited from direct control, deduplicates trustee-target-capability relationships, and
selects only candidate paths suitable for later reversible behavioral validation.

This stage is local only. It performs no network operations, AD queries, directory writes, password
resets, membership changes, SPN changes, RBCD changes, key-credential changes, owner changes, or DACL changes.
.NOTES
Version: 0.1.0
Package identity: MSADPT-AD-OBJECT-CONTROL-CORRELATION
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [ValidateNotNullOrEmpty()]
    [string]$BaselineDirectory,

    [string]$OutputDirectory,
    [switch]$Quiet,
    [switch]$NoColor
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'
$PackageIdentity = 'MSADPT-AD-OBJECT-CONTROL-CORRELATION'
$PackageVersion = '0.1.0'

function Write-Step {
    param([string]$Status,[string]$Message,[ConsoleColor]$Color=[ConsoleColor]::Gray)
    if ($Quiet) { return }
    $Text = '[{0,-10}] {1}' -f $Status,$Message
    if ($NoColor) { Write-Host $Text } else { Write-Host $Text -ForegroundColor $Color }
}
function Require-File {
    param([string]$Path,[string]$Label)
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "RequiredFileMissing [$Label]: $Path" }
    if ((Get-Item -LiteralPath $Path).Length -eq 0) { throw "RequiredFileEmpty [$Label]: $Path" }
}
function Write-JsonArray {
    param([object[]]$Rows,[string]$Path,[int]$Depth=15)
    $Array = @($Rows)
    if ($Array.Count -eq 0) {
        [IO.File]::WriteAllText($Path,"[]`r`n",(New-Object Text.UTF8Encoding($false)))
    }
    else {
        $Array | ConvertTo-Json -Depth $Depth | Set-Content -LiteralPath $Path -Encoding UTF8
    }
    $Check = @(Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json -ErrorAction Stop)
    if ($Check.Count -ne $Array.Count) { throw "JsonArrayRoundTripMismatch: $Path" }
}
function Write-JsonDocument {
    param([object]$Document,[string]$Path,[int]$Depth=15)
    $Document | ConvertTo-Json -Depth $Depth | Set-Content -LiteralPath $Path -Encoding UTF8
    $null = Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json -ErrorAction Stop
}
function Convert-HtmlText {
    param([object]$Value)
    return [Net.WebUtility]::HtmlEncode([string]$Value)
}
function Normalize-GuidText {
    param([object]$Value)
    $Text = [string]$Value
    if ([string]::IsNullOrWhiteSpace($Text)) { return '00000000-0000-0000-0000-000000000000' }
    return $Text.Trim('{}').ToLowerInvariant()
}
function Get-SemanticCapability {
    param([object]$Ace)

    $Rights = [string]$Ace.ActiveDirectoryRights
    $TargetType = [string]$Ace.TargetObjectType
    $Guid = Normalize-GuidText $Ace.ObjectTypeGuid
    $Capabilities = New-Object 'System.Collections.Generic.List[string]'

    $KnownGuidMap = @{
        'bf9679c0-0de6-11d0-a285-00aa003049e2' = 'WriteGroupMembership'
        'bf967a7f-0de6-11d0-a285-00aa003049e2' = 'WriteServicePrincipalName'
        '3f78c3e5-f79a-46bd-a0b8-9d18116ddc79' = 'WriteRBCD'
        '5b47d60f-6090-40b2-9f37-2a4de88f3063' = 'WriteKeyCredentialLink'
        '00299570-246d-11d0-a768-00aa006e0529' = 'ResetPassword'
        'ab721a53-1e2f-11d0-9819-00aa0040529b' = 'ChangePassword'
        '1131f6aa-9c07-11d1-f79f-00c04fc2dcd2' = 'ReplicatingDirectoryChanges'
        '1131f6ad-9c07-11d1-f79f-00c04fc2dcd2' = 'ReplicatingDirectoryChangesAll'
        '89e95b76-444d-4c62-991a-0facbeda640c' = 'ReplicatingDirectoryChangesFilteredSet'
        'bf9679e8-0de6-11d0-a285-00aa003049e2' = 'WriteUserAccountControl'
    }

    if ($Rights -match 'GenericAll') { $Capabilities.Add('GenericAll') }
    if ($Rights -match 'WriteDacl') { $Capabilities.Add('WriteDacl') }
    if ($Rights -match 'WriteOwner') { $Capabilities.Add('WriteOwner') }
    if ($Rights -match 'GenericWrite') { $Capabilities.Add('GenericWrite') }

    if ($KnownGuidMap.ContainsKey($Guid)) {
        $Capabilities.Add($KnownGuidMap[$Guid])
    }
    elseif ($Guid -eq '00000000-0000-0000-0000-000000000000') {
        if ($Rights -match 'WriteProperty|GenericWrite|GenericAll') {
            switch ($TargetType) {
                'Group' { $Capabilities.Add('BroadGroupControl') }
                'Computer' { $Capabilities.Add('BroadComputerControl') }
                'User' { $Capabilities.Add('BroadUserControl') }
                'Domain' { $Capabilities.Add('BroadDomainControl') }
                'OrganizationalUnit' { $Capabilities.Add('BroadOuControl') }
            }
        }
        if ($Rights -match 'ExtendedRight' -and $TargetType -eq 'User') {
            $Capabilities.Add('BroadUserExtendedRights')
        }
    }

    return @($Capabilities.ToArray() | Sort-Object -Unique)
}
function Get-ValidatorForCapability {
    param([string]$Capability)
    switch ($Capability) {
        'WriteGroupMembership' {'GroupMembershipBehavioralValidation'}
        'ResetPassword' {'PasswordResetRightBehavioralValidation'}
        'WriteServicePrincipalName' {'SpnWriteBehavioralValidation'}
        'WriteRBCD' {'RbcdWriteBehavioralValidation'}
        'WriteKeyCredentialLink' {'KeyCredentialWriteBehavioralValidation'}
        'WriteDacl' {'DaclControlBehavioralValidation'}
        'WriteOwner' {'OwnershipControlBehavioralValidation'}
        'ReplicatingDirectoryChanges' {'ReplicationRightsValidation'}
        'ReplicatingDirectoryChangesAll' {'ReplicationRightsValidation'}
        'ReplicatingDirectoryChangesFilteredSet' {'ReplicationRightsValidation'}
        'WriteUserAccountControl' {'UserAccountControlBehavioralValidation'}
        'GenericAll' {'GenericObjectControlBehavioralValidation'}
        'GenericWrite' {'GenericObjectControlBehavioralValidation'}
        'BroadGroupControl' {'GroupControlSemanticRefinement'}
        'BroadComputerControl' {'ComputerControlSemanticRefinement'}
        'BroadUserControl' {'UserControlSemanticRefinement'}
        'BroadDomainControl' {'DomainControlSemanticRefinement'}
        'BroadOuControl' {'OuControlSemanticRefinement'}
        default {'SemanticRefinementRequired'}
    }
}
function Get-Priority {
    param([string]$Capability,[object]$Ace)
    if ($Capability -in @('ReplicatingDirectoryChangesAll','ResetPassword','WriteRBCD','WriteKeyCredentialLink') -and $Ace.TargetAdminCount -eq 1) { return 'P1' }
    if ($Capability -in @('GenericAll','WriteDacl','WriteOwner') -and $Ace.TargetAdminCount -eq 1) { return 'P1' }
    if ($Capability -in @('ReplicatingDirectoryChanges','ReplicatingDirectoryChangesAll','ReplicatingDirectoryChangesFilteredSet','ResetPassword','WriteRBCD','WriteKeyCredentialLink','WriteGroupMembership','WriteServicePrincipalName','WriteDacl','WriteOwner')) { return 'P2' }
    if ($Capability -in @('GenericAll','GenericWrite','BroadGroupControl','BroadComputerControl','BroadUserControl','BroadDomainControl','BroadOuControl')) { return 'P3' }
    return 'P4'
}

try {
    Write-Step 'START' "$PackageIdentity v$PackageVersion" Cyan
    Write-Step 'INFO' 'Local correlation only. No network or directory operations will occur.' DarkGray

    if (-not (Test-Path -LiteralPath $BaselineDirectory -PathType Container)) { throw "BaselineDirectoryMissing: $BaselineDirectory" }
    $AcePath = Join-Path $BaselineDirectory 'dangerous-ace-inventory.json'
    $SummarySourcePath = Join-Path $BaselineDirectory 'ad-object-control-summary.json'
    Require-File $AcePath 'Dangerous ACE inventory'
    Require-File $SummarySourcePath 'Object-control summary'

    if ($null -eq $OutputDirectory -or $OutputDirectory.Trim().Length -eq 0) {
        $OutputDirectory = Join-Path $BaselineDirectory 'SemanticCorrelation-v0.1.0'
    }
    if (Test-Path -LiteralPath $OutputDirectory -PathType Container) {
        if (@(Get-ChildItem -LiteralPath $OutputDirectory -Force -ErrorAction SilentlyContinue).Count -gt 0) { throw "OutputDirectoryNotEmpty: $OutputDirectory" }
    }
    New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

    Write-Step 'LOAD' 'Loading raw ACE evidence. Large environments may require several minutes.' Yellow
    $AceRows = @(Get-Content -LiteralPath $AcePath -Raw | ConvertFrom-Json -ErrorAction Stop)
    $SourceSummary = Get-Content -LiteralPath $SummarySourcePath -Raw | ConvertFrom-Json -ErrorAction Stop
    Write-Step 'OK' "Loaded $($AceRows.Count) ACE record(s)." Green

    $SemanticRows = New-Object 'System.Collections.Generic.List[object]'
    $Processed = 0
    foreach ($Ace in $AceRows) {
        $Processed++
        if ($Processed -eq 1 -or $Processed % 50000 -eq 0 -or $Processed -eq $AceRows.Count) {
            $Percent = [int](($Processed/[double]$AceRows.Count)*100)
            Write-Step 'PROCESS' "Semantic resolution $Processed/$($AceRows.Count) ($Percent%)." DarkCyan
        }

        if ([bool]$Ace.RoutineAdministrative) { continue }
        if ($Ace.TrusteeEnabled -eq $false) { continue }

        $Capabilities = @(Get-SemanticCapability $Ace)
        foreach ($Capability in $Capabilities) {
            if ($Capability -eq 'BroadUserExtendedRights') { continue }
            $SemanticRows.Add([pscustomobject][ordered]@{
                Trustee=[string]$Ace.Trustee;TrusteeSamAccountName=[string]$Ace.TrusteeSamAccountName
                TrusteeResolved=[bool]$Ace.TrusteeResolved;TrusteeEnabled=$Ace.TrusteeEnabled
                TrusteeObjectType=[string]$Ace.TrusteeObjectType;TrusteeAdminCount=$Ace.TrusteeAdminCount
                TargetObjectType=[string]$Ace.TargetObjectType;TargetName=[string]$Ace.TargetName
                TargetSamAccountName=[string]$Ace.TargetSamAccountName
                TargetDistinguishedName=[string]$Ace.TargetDistinguishedName
                TargetEnabled=$Ace.TargetEnabled;TargetAdminCount=$Ace.TargetAdminCount
                Capability=$Capability;SourceRights=[string]$Ace.ActiveDirectoryRights
                ObjectTypeGuid=(Normalize-GuidText $Ace.ObjectTypeGuid)
                IsInherited=[bool]$Ace.IsInherited;InheritanceType=[string]$Ace.InheritanceType
            })
        }
    }

    Write-Step 'DEDUPE' "Deduplicating $($SemanticRows.Count) semantic relationship row(s)." Yellow
    $Grouped = @(
        $SemanticRows |
        Group-Object {
            '{0}|{1}|{2}' -f ([string]$_.Trustee).ToLowerInvariant(),([string]$_.TargetDistinguishedName).ToLowerInvariant(),[string]$_.Capability
        }
    )

    $CorrelatedRows = New-Object 'System.Collections.Generic.List[object]'
    foreach ($Group in $Grouped) {
        $Rows = @($Group.Group)
        $First = $Rows[0]
        $DirectCount = @($Rows | Where-Object { -not [bool]$_.IsInherited }).Count
        $InheritedCount = @($Rows | Where-Object { [bool]$_.IsInherited }).Count
        $Validator = Get-ValidatorForCapability $First.Capability
        $Priority = Get-Priority $First.Capability $First
        $BehavioralReady = ($Validator -notmatch 'SemanticRefinementRequired|SemanticRefinement')

        $CorrelatedRows.Add([pscustomobject][ordered]@{
            CandidateId=('ACL-CORR-{0:D6}' -f $CorrelatedRows.Count)
            Priority=$Priority;Trustee=$First.Trustee;TrusteeSamAccountName=$First.TrusteeSamAccountName
            TrusteeResolved=$First.TrusteeResolved;TrusteeEnabled=$First.TrusteeEnabled
            TrusteeObjectType=$First.TrusteeObjectType;TrusteeAdminCount=$First.TrusteeAdminCount
            TargetObjectType=$First.TargetObjectType;TargetName=$First.TargetName
            TargetSamAccountName=$First.TargetSamAccountName;TargetDistinguishedName=$First.TargetDistinguishedName
            TargetEnabled=$First.TargetEnabled;TargetAdminCount=$First.TargetAdminCount
            Capability=$First.Capability;ContributingAceCount=$Rows.Count
            DirectAceCount=$DirectCount;InheritedAceCount=$InheritedCount
            SourceRights=@($Rows.SourceRights | Sort-Object -Unique)
            ObjectTypeGuids=@($Rows.ObjectTypeGuid | Sort-Object -Unique)
            NextValidator=$Validator;BehavioralValidationReady=$BehavioralReady
            EvidenceState=if($BehavioralReady){'Semantic capability resolved; effective-control validation pending'}else{'Semantic refinement required'}
            Interpretation='A deduplicated trustee-to-target capability was identified. Trustee reachability, deny precedence, protected-object behavior, and real impact remain unproven.'
        })
    }

    $BehavioralCandidates = @(
        $CorrelatedRows |
        Where-Object {
            $_.BehavioralValidationReady -and
            $_.TrusteeResolved -and
            $_.TrusteeEnabled -ne $false -and
            $_.Priority -in @('P1','P2')
        } |
        Sort-Object Priority,Capability,TargetName,Trustee
    )

    $SemanticPath=Join-Path $OutputDirectory 'semantic-control-relationships.json'
    $SemanticCsv=Join-Path $OutputDirectory 'semantic-control-relationships.csv'
    $CorrelatedPath=Join-Path $OutputDirectory 'deduplicated-control-candidates.json'
    $CorrelatedCsv=Join-Path $OutputDirectory 'deduplicated-control-candidates.csv'
    $BehavioralPath=Join-Path $OutputDirectory 'behavioral-validation-candidates.json'
    $BehavioralCsv=Join-Path $OutputDirectory 'behavioral-validation-candidates.csv'
    Write-JsonArray $SemanticRows.ToArray() $SemanticPath
    $SemanticRows | Export-Csv -LiteralPath $SemanticCsv -NoTypeInformation -Encoding UTF8
    Write-JsonArray $CorrelatedRows.ToArray() $CorrelatedPath
    $CorrelatedRows | Export-Csv -LiteralPath $CorrelatedCsv -NoTypeInformation -Encoding UTF8
    Write-JsonArray $BehavioralCandidates $BehavioralPath
    $BehavioralCandidates | Export-Csv -LiteralPath $BehavioralCsv -NoTypeInformation -Encoding UTF8

    $CapabilityCounts = @($CorrelatedRows | Group-Object Capability | Sort-Object Count -Descending | ForEach-Object { [pscustomobject]@{Capability=$_.Name;Count=$_.Count} })
    $Summary=[pscustomobject][ordered]@{
        SchemaVersion='1.0';PackageIdentity=$PackageIdentity;PackageVersion=$PackageVersion
        Status='Completed';GeneratedUtc=(Get-Date).ToUniversalTime().ToString('o')
        SourceDirectory=$BaselineDirectory;Domain=[string]$SourceSummary.Domain.DnsRoot
        Counts=[pscustomobject]@{
            RawAceRows=$AceRows.Count;SemanticRows=$SemanticRows.Count
            DeduplicatedCandidates=$CorrelatedRows.Count;BehavioralValidationCandidates=$BehavioralCandidates.Count
            P1=@($CorrelatedRows|Where-Object{$_.Priority-eq'P1'}).Count
            P2=@($CorrelatedRows|Where-Object{$_.Priority-eq'P2'}).Count
            P3=@($CorrelatedRows|Where-Object{$_.Priority-eq'P3'}).Count
            P4=@($CorrelatedRows|Where-Object{$_.Priority-eq'P4'}).Count
        }
        CapabilityCounts=$CapabilityCounts
        InterpretationBoundary=@(
            'Semantic GUID resolution does not prove trustee compromise or effective access.',
            'Inherited and direct ACE contributions are preserved separately.',
            'Behavioral candidates require effective-access validation and a safe reversible operation.',
            'No vulnerability is produced from this local correlation stage.'
        )
        Safety=[pscustomobject]@{NetworkActivity='None';DirectoryQueries='None';DirectoryChanges='None';OllamaActivity='None'}
    }
    $SummaryPath=Join-Path $OutputDirectory 'ad-object-control-correlation-summary.json'
    Write-JsonDocument $Summary $SummaryPath

    $Top=@($BehavioralCandidates|Select-Object -First 100)
    $TopHtml=($Top|ForEach-Object{'<tr><td>{0}</td><td>{1}</td><td>{2}</td><td>{3}</td><td>{4}</td><td>{5}</td></tr>'-f(Convert-HtmlText $_.Priority),(Convert-HtmlText $_.Trustee),(Convert-HtmlText $_.TargetObjectType),(Convert-HtmlText $_.TargetName),(Convert-HtmlText $_.Capability),(Convert-HtmlText $_.NextValidator)})-join"`n"
    $ReportPath=Join-Path $OutputDirectory 'MSADPT-AD-Object-Control-Correlation.html'
    $Html=@"
<!doctype html><html><head><meta charset="utf-8"><title>MSADPT AD Object-Control Correlation</title><style>body{font-family:Segoe UI,Arial;margin:32px;color:#17202a}h1,h2{color:#0b5cab}.card{border:1px solid #ccd6dd;border-radius:8px;padding:16px;margin:14px 0}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccd6dd;padding:8px;text-align:left;vertical-align:top}th{background:#eaf2f8}.note{color:#5d6d7e}</style></head><body><h1>MSADPT AD Object-Control Correlation</h1><div class="card"><b>Domain:</b> $(Convert-HtmlText $Summary.Domain)<br><b>Raw ACE rows:</b> $($AceRows.Count)<br><b>Semantic rows:</b> $($SemanticRows.Count)<br><b>Deduplicated candidates:</b> $($CorrelatedRows.Count)<br><b>Behavioral validation candidates:</b> $($BehavioralCandidates.Count)<br><b>Network activity:</b> None</div><h2>Top Behavioral Candidates</h2><table><tr><th>Priority</th><th>Trustee</th><th>Target Type</th><th>Target</th><th>Capability</th><th>Next Validator</th></tr>$TopHtml</table><h2>Evidence</h2><ul><li><a href="deduplicated-control-candidates.csv">Deduplicated candidates</a></li><li><a href="behavioral-validation-candidates.csv">Behavioral candidates</a></li><li><a href="ad-object-control-correlation-summary.json">Structured summary</a></li><li><a href="../MSADPT-AD-Object-Control-Report.html">Baseline report</a></li></ul><p class="note">Candidates are not vulnerabilities. Effective access and real reversible impact must be reproduced before reporting a finding.</p></body></html>
"@
    [IO.File]::WriteAllText($ReportPath,$Html,(New-Object Text.UTF8Encoding($false)))

    $Files=@(Get-ChildItem -LiteralPath $OutputDirectory -File|Where-Object{$_.Name-ne'evidence-manifest.json'}|Sort-Object Name)
    $ManifestRows=@(foreach($File in $Files){[pscustomobject]@{Name=$File.Name;Size=[int64]$File.Length;SHA256=(Get-FileHash -LiteralPath $File.FullName -Algorithm SHA256).Hash}})
    $ManifestPath=Join-Path $OutputDirectory 'evidence-manifest.json'
    Write-JsonDocument ([pscustomobject]@{SchemaVersion='1.0';Status='Completed';FileCount=$ManifestRows.Count;Files=$ManifestRows}) $ManifestPath

    Write-Step 'DONE' "Correlation complete: raw=$($AceRows.Count), semantic=$($SemanticRows.Count), deduplicated=$($CorrelatedRows.Count), behavioral=$($BehavioralCandidates.Count)." Green
    [pscustomobject][ordered]@{
        Status='Passed';PackageIdentity=$PackageIdentity;PackageVersion=$PackageVersion;Domain=$Summary.Domain
        RawAceCount=$AceRows.Count;SemanticRelationshipCount=$SemanticRows.Count
        DeduplicatedCandidateCount=$CorrelatedRows.Count;BehavioralValidationCandidateCount=$BehavioralCandidates.Count
        P1Count=$Summary.Counts.P1;P2Count=$Summary.Counts.P2;P3Count=$Summary.Counts.P3;P4Count=$Summary.Counts.P4
        OutputDirectory=$OutputDirectory;HtmlReportPath=$ReportPath;SummaryPath=$SummaryPath;ManifestPath=$ManifestPath
        NetworkActivity='None';DirectoryQueries='None';DirectoryChanges='None';OllamaActivity='None'
    }
}
catch {
    Write-Step 'FAIL' $_.Exception.Message Red
    throw
}
