<#
.SYNOPSIS
Selectively reprocesses MSADPT Directory Control token, schema, effective-access, and reporting stages.
.NOTES
Version: 1.0.2
#>
[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$EngagementDirectory,[string]$Server,[PSCredential]$Credential,[int]$MaximumTokenDepth=16,[switch]$NoColor)
Set-StrictMode -Version 2.0;$ErrorActionPreference='Stop';$Version='1.0.2';$Root=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path;function Show([string]$s,[string]$m,[ConsoleColor]$c=[ConsoleColor]::Gray){$t='[{0,-12}] {1}'-f$s,$m;if($NoColor){Write-Host$t}else{Write-Host$t -ForegroundColor$c}};function ReadJson([string]$p){Get-Content $p -Raw|ConvertFrom-Json};function H([object]$v){[Net.WebUtility]::HtmlEncode([string]$v)}
$EngagementDirectory=[IO.Path]::GetFullPath($EngagementDirectory);$Evidence=Join-Path $EngagementDirectory 'evidence\DirectoryControl';$Reduction=Join-Path $EngagementDirectory 'analysis\DirectoryControlReduction';$Token=Join-Path $EngagementDirectory 'evidence\DirectoryControlToken';$Schema=Join-Path $EngagementDirectory 'evidence\DirectoryControlSchema';$Effective=Join-Path $EngagementDirectory 'analysis\DirectoryControlEffectiveAccess';$Reports=Join-Path $EngagementDirectory 'reports';$State=Join-Path $EngagementDirectory 'state\stages';$candidate=Join-Path $Reduction 'directory-control-prioritized-target-details.csv';foreach($required in @((Join-Path $Evidence 'directory-control-ace-inventory.csv'),$candidate)){if(-not(Test-Path $required)){throw "ReusableEvidenceMissing: $required"}};Show START "Selective effective-access reprocessing v$Version" Cyan;Show REUSE 'Existing Directory Control ACL evidence. No ACL recollection.' DarkGreen;Show REUSE 'Existing candidate-reduction evidence. No candidate reduction.' DarkGreen
$tokenRunner=Join-Path $Root 'Modules\ObjectControl\Invoke-MSADPTDirectoryControlTokenEvidence-v1.0.1.ps1';$schemaRunner=Join-Path $Root 'Modules\ObjectControl\Invoke-MSADPTDirectoryControlSchemaClassMap-v1.0.0.ps1';$evalRunner=Join-Path $Root 'Modules\ObjectControl\Invoke-MSADPTDirectoryControlEffectiveAccess-v1.0.2.ps1';foreach($p in @($tokenRunner,$schemaRunner,$evalRunner)){if(-not(Test-Path $p)){throw "ComponentMissing: $p"}}
$Target=if($Server){$Server}else{'current domain'};Show EXECUTE "Trustee token collection through $Target over ADWS/LDAP. Read-only; changes=None." Magenta;if(Test-Path $Token){Remove-Item $Token -Recurse -Force};$p=@{CandidateEvidencePath=$candidate;OutputDirectory=$Token;MaximumDepth=$MaximumTokenDepth;NoColor=[bool]$NoColor};if($Server){$p.Server=$Server};if($Credential){$p.Credential=$Credential};$null=&$tokenRunner @p
Show EXECUTE 'Schema class GUID collection through ADWS/LDAP. Read-only; changes=None.' Magenta;if(Test-Path $Schema){Remove-Item $Schema -Recurse -Force};$p=@{OutputDirectory=$Schema;NoColor=[bool]$NoColor};if($Server){$p.Server=$Server};if($Credential){$p.Credential=$Credential};$null=&$schemaRunner @p
Show EXECUTE 'Offline token-wide effective-access evaluation.' Cyan;if(Test-Path $Effective){Remove-Item $Effective -Recurse -Force};$null=&$evalRunner -DirectoryControlEvidenceDirectory $Evidence -CandidateReductionDirectory $Reduction -OutputDirectory $Effective -TokenEvidencePath (Join-Path $Token 'directory-control-token-evidence.csv') -SchemaClassMapPath (Join-Path $Schema 'directory-control-schema-class-map.csv') -NoColor:$NoColor
$ts=ReadJson (Join-Path $Token 'directory-control-token-summary.json');$ss=ReadJson (Join-Path $Schema 'directory-control-schema-class-summary.json');$es=ReadJson (Join-Path $Effective 'directory-control-effective-access-summary.json');$rows=@(Import-Csv (Join-Path $Effective 'directory-control-effective-access-evaluations.csv'));$reasons=$rows|Group-Object Reason|Sort-Object Count -Descending;$reasonHtml=@($reasons|ForEach-Object{"<tr><td>$(H $_.Name)</td><td>$($_.Count)</td></tr>"})-join'';$confirmed=@($rows|Where-Object Disposition -eq'EffectiveControlConfirmed');$confirmedHtml=@($confirmed|Select-Object -First 50|ForEach-Object{"<tr><td>$(H $_.ValidationPriority)</td><td>$(H $_.Trustee)</td><td>$(H $_.Capability)</td><td>$(H $_.TargetName)</td><td>$(H $_.Reason)</td></tr>"})-join'';New-Item -ItemType Directory -Path $Reports,$State -Force|Out-Null
$html=@" 
<!doctype html><html><head><meta charset="utf-8"><title>MSADPT Directory Control Effective Access</title><style>body{font-family:Segoe UI,Arial;margin:32px;color:#17202a}h1,h2{color:#0b5cab}.card{border:1px solid #ccd6dd;border-radius:8px;padding:16px;margin:14px 0}.warn{border-left:5px solid #d68910}table{border-collapse:collapse;width:100%}th,td{border:1px solid #ccd6dd;padding:8px;text-align:left}th{background:#eaf2f8}</style></head><body><h1>Directory Control Effective Access</h1><div class="card"><b>Reused:</b> ACL inventory and candidate reduction<br><b>Token principals:</b> $($ts.PrincipalCount)<br><b>Resolved principals:</b> $($ts.ResolvedPrincipalCount)<br><b>Unresolved principals:</b> $($ts.UnresolvedPrincipalCount)<br><b>Complete tokens:</b> $($ts.CompletePrincipalCount)<br><b>Schema classes:</b> $($ss.ClassCount)<br><b>Evaluations:</b> $($rows.Count)<br><b>Effective control confirmed:</b> $($confirmed.Count)<br><b>Effective control not established:</b> $(@($rows|Where-Object Disposition -eq'EffectiveControlNotEstablished').Count)<br><b>Not applicable:</b> $(@($rows|Where-Object Disposition -eq'NotApplicable').Count)<br><b>Inconclusive:</b> $(@($rows|Where-Object Disposition -eq'Inconclusive').Count)</div><div class="card warn"><b>Interpretation boundary:</b> Effective control confirms only applicable permission for collected token evidence. Impact was not reproduced and no vulnerability is automatically confirmed.</div><h2>Disposition reasons</h2><table><tr><th>Reason</th><th>Count</th></tr>$reasonHtml</table><h2>Confirmed permission candidates</h2><table><tr><th>Validation Priority</th><th>Trustee</th><th>Capability</th><th>Target</th><th>Reason</th></tr>$confirmedHtml</table><h2>Evidence</h2><ul><li><a href="../analysis/DirectoryControlEffectiveAccess/directory-control-effective-access-evaluations.csv">Evaluations</a></li><li><a href="../analysis/DirectoryControlEffectiveAccess/directory-control-effective-access-ace-trace.csv">ACE trace</a></li><li><a href="../evidence/DirectoryControlToken/directory-control-token-evidence.csv">Token evidence</a></li><li><a href="../evidence/DirectoryControlSchema/directory-control-schema-class-map.csv">Schema class map</a></li></ul></body></html>
"@;$report=Join-Path $Reports 'MSADPT-Directory-Control-Effective-Access.html';[IO.File]::WriteAllText($report,$html,(New-Object Text.UTF8Encoding($false)));$stage=[pscustomobject]@{SchemaVersion='1.0';Stage='DirectoryControlEffectiveAccess';Status='Completed';Disposition=[string]$es.Disposition;GeneratedUtc=(Get-Date).ToUniversalTime().ToString('o');ReusedAclEvidence=$true;ReusedReductionEvidence=$true;TokenPrincipalCount=[int]$ts.PrincipalCount;ResolvedPrincipalCount=[int]$ts.ResolvedPrincipalCount;CompleteTokenCount=[int]$ts.CompletePrincipalCount;SchemaClassCount=[int]$ss.ClassCount;EvaluationCount=$rows.Count;EffectiveControlConfirmedCount=$confirmed.Count;InconclusiveCount=@($rows|Where-Object Disposition -eq'Inconclusive').Count;ImpactReproduced=$false;VulnerabilityConfirmed=$false;ReportPath=$report};$stage|ConvertTo-Json -Depth 10|Set-Content (Join-Path $State 'directory-control-effective-access.json') -Encoding UTF8;Show REPORT $report Cyan;Show DONE "Resolved=$($ts.ResolvedPrincipalCount)/$($ts.PrincipalCount); classes=$($ss.ClassCount); confirmed=$($confirmed.Count); inconclusive=$(@($rows|Where-Object Disposition -eq'Inconclusive').Count)." Green;[pscustomobject]@{Status='Passed';PipelineVersion=$Version;EngagementDirectory=$EngagementDirectory;ReusedAclEvidence=$true;ReusedReductionEvidence=$true;ResolvedPrincipalCount=[int]$ts.ResolvedPrincipalCount;CompleteTokenCount=[int]$ts.CompletePrincipalCount;SchemaClassCount=[int]$ss.ClassCount;EvaluationCount=$rows.Count;EffectiveControlConfirmedCount=$confirmed.Count;InconclusiveCount=@($rows|Where-Object Disposition -eq'Inconclusive').Count;ImpactReproduced=$false;VulnerabilityConfirmed=$false;HtmlReportPath=$report;NetworkActivity='ReadOnlyADQueries';RemoteChanges='None'}
